"""add delivery partner

Revision ID: 652e3bf5a664
Revises: 
Create Date: 2025-07-05 22:56:21.409561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '652e3bf5a664'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_partner',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('zip_code', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('serviceable_zip_codes', sa.ARRAY(sa.INTEGER()), nullable=True),
    sa.Column('max_handling_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('seller', 'name')
    op.drop_column('seller', 'email_verified')
    op.drop_column('seller', 'zip_code')
    op.drop_column('seller', 'email')
    op.drop_column('seller', 'address')
    op.drop_column('seller', 'password_hash')
    op.add_column('shipment', sa.Column('delivery_partner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'shipment', 'delivery_partner', ['delivery_partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.drop_column('shipment', 'delivery_partner_id')
    op.add_column('seller', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('seller', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('seller', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('seller', sa.Column('zip_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('seller', sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('seller', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('delivery_partner')
    # ### end Alembic commands ###
