"""test

Revision ID: 696dcaffa311
Revises: 652e3bf5a664
Create Date: 2025-07-29 19:12:17.359572

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '696dcaffa311'
down_revision: Union[str, Sequence[str], None] = '652e3bf5a664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_partner', 'zip_code')
    op.drop_column('delivery_partner', 'address')
    op.create_foreign_key(None, 'shipment', 'seller', ['seller_id'], ['id'])
    op.drop_column('shipment', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('status', postgresql.ENUM('placed', 'in_transit', 'out_for_delivery', 'delivered', name='shipmentstatus'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.add_column('delivery_partner', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('delivery_partner', sa.Column('zip_code', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
